openapi: 3.0.0
info:
    title: Hello World
    version: '1.0'
servers:
    -
        url: 'http://localhost:8080'
paths:
    '/greeting/{name}':
        post:
            parameters:
                -
                    name: name
                    description: Name of the person to greet.
                    schema:
                        $ref: '#/components/schemas/person'
                    in: path
                    required: true
            responses:
                '200':
                    content:
                        text/plain:
                            schema:
                                $ref: '#/components/schemas/message'
                    description: greeting response
            operationId: hello.post_greeting
            summary: Generate greeting
            description: Generates a greeting message.
components:
    schemas:
        person:
            required:
                - name
            type: object
            properties:
                name:
                    description: Persons Name
                    type: string
                    example: Dave
        message:
            required:
                - message
            type: object
            properties:
                message:
                    description: Message returned
                    type: string
                    example: Hello Dave
