---
modelPackage: ${groupId}.${artifactId}.models
apiPackage: ${groupId}.${artifactId}.api
invokerPackage: ${groupId}.${artifactId}
groupId: ${groupId}
artifactId: ${artifactId}
dateLibrary: java8
booleanGetterPrefix: is
artifactVersion: 1.0.0
hideGenerationTimestamp: true